# tls_server_config:
#     client_auth_type: RequireAndVerifyClientCert
#     cert_file: /etc/node_exporter/server-cert.pem
#     key_file: /etc/node_exporter/server-key.pem
#     client_ca_file: /etc/node_exporter/ca.pem
basic_auth_users:
    node_exporter: {{HT_PASSWD_NODE_EXPORTER}}